#Base method/path
/:
  controller: Base
  action: index
  method: GET

#Auth method/path
/signup:
  controller: Auth
  action: renderSignup
  method: GET

/login:
  controller: Auth
  action: renderLogin
  method: GET

/addUser:
  controller: Auth
  action: signup
  method: POST

/signinUser:
  controller: Auth
  action: signin
  method: POST

/updateUser:
  controller: Auth
  action: updateUser

/logout:
  controller: Auth
  action: logout

/deleteUser:
  controller: Auth
  action: deleteUser

/setAdmin:
  controller: Auth
  action: setAdminUser

/profil:
  controller: Auth
  action: renderProfil

/dashboard:
  controller: Auth
  action: renderDashboard

/users:
  controller: Auth
  action: renderUsers

/resetPassword:
  controller: Auth
  action: renderResetPassword

/modifyPassword:
  controller: Auth
  action: renderModifyPassword

/updatePassword:
  controller: Auth
  action: updatePassword

/activation:
  controller: EmailVerification
  action: activateAccount

/sendNewPassword:
  controller: EmailVerification
  action: sendResetPwdMail

/createUser:
  controller: Auth
  action: createUser
  method: POST

/createBankAccount:
  controller: BankAccount
  action: create
  method: POST

/formBankAccount:
  controller: BankAccount
  action: formCreate
