#Base method/path
/:
  controller: Auth
  action: renderHome
  method: GET
  access: guest

/abonnement:
  controller: Auth
  action: renderAbonnement
  method: GET

#Auth method/path
/signup:
  controller: Auth
  action: renderSignup
  method: GET
  access: guest

/login:
  controller: Auth
  action: renderLogin
  method: GET
  access: guest

/addUser:
  controller: Auth
  action: signup
  method: POST
  access: guest

/signinUser:
  controller: Auth
  action: signin
  method: POST
  access: guest

/updateUser:
  controller: Auth
  action: updateUser
  method: POST
  access: auth

/logout:
  controller: Auth
  action: logout
  method: POST
  access: auth

/deleteUser:
  controller: Auth
  action: deleteUser
  method: POST
  access: auth

/setAdmin:
  controller: Auth
  action: setAdminUser
  method: POST
  access: auth

/profil:
  controller: Auth
  action: renderProfil
  method: GET
  access: auth

/users:
  controller: Auth
  action: renderUsers
  method: GET
  access: auth

/resetPassword:
  controller: Auth
  action: renderResetPassword
  method: GET

/modifyPassword:
  controller: Auth
  action: renderModifyPassword
  method: GET

/updatePassword:
  controller: Auth
  action: updatePassword
  method: POST

/activation:
  controller: EmailVerification
  action: activateAccount
  method: GET

/sendNewPassword:
  controller: EmailVerification
  action: sendResetPwdMail
  method: POST

/createUser:
  controller: Auth
  action: createUser
  method: POST

/createBankAccount:
  controller: BankAccount
  action: create
  method: POST
  access: auth

/formBankAccount:
  controller: BankAccount
  action: formCreate
  access: auth

/accounts:
  controller: BankAccount
  action: renderAccounts
  method: GET

/manageAccounts:
  controller: BankAccount
  action: renderManageAccounts
  method: GET
  access: auth

/accountDetails:
  controller: BankAccount
  action: renderAccountDetails
  method: GET
  access: auth

/subscribe:
  controller: Subscription
  action: subscribe
  method: POST
  access: auth

/subscribeSuccess:
  controller: Subscription
  action: subscribeSuccess
  method: GET
  access: auth

/unsubscribe:
  controller: Subscription
  action: unsubscribe
  method: POST
  access: auth

# Transactions
/transactions:
  controller: Transaction
  action: index
  method: GET
  access: auth

/transactions/create:
  controller: Transaction
  action: create
  method: POST
  access: auth

/transactions/form:
  controller: Transaction
  action: formCreate
  method: GET
  access: auth

/transactions/edit:
  controller: Transaction
  action: edit
  method: GET
  access: auth

/transactions/update:
  controller: Transaction
  action: edit
  method: POST
  access: auth

/transactions/delete:
  controller: Transaction
  action: delete
  method: POST
  access: auth

/transactions/summary:
  controller: Transaction
  action: summary
  method: GET
  access: auth
